[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "S",   # flake8-bandit
    "T20", # flake8-print
    "SIM", # flake8-simplify
    "RUF", # Ruff-specific rules
]

ignore = [
    "E501",  # line too long, handled by formatter
    "B008",  # do not perform function calls in argument defaults
    "S101",  # use of assert detected
    "T201",  # print found
    "S603",  # subprocess call: check for execution of untrusted input
    "S607",  # starting a process with a partial executable path
    "S311",  # suspicious-non-cryptographic-random-usage (acceptable for simulation/testing)
    "E402",  # module-import-not-at-top-of-file (acceptable for sys.path modification)
    "S104",  # hardcoded-bind-all-interfaces (acceptable for dev servers)
    "S110",  # try-except-pass (acceptable for error handling)
    "S108",  # hardcoded-temp-file (acceptable for demos/examples)
    "S310",  # suspicious-url-open-usage (acceptable for test validation)
    "S314",  # suspicious-xml-element-tree-usage (acceptable for test reports)
    "N815",  # mixed-case-variable-in-class-scope (acceptable for external APIs)
    "RUF001", # ambiguous-unicode-character-string (acceptable for emoji in UI)
    "RUF012", # mutable-class-default (acceptable for config classes)
    "SIM102", # collapsible-if (acceptable for readability)
    "SIM117", # multiple-with-statements (acceptable for clarity)
    "B023",  # function-uses-loop-variable (acceptable in specific contexts)
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**/*.py" = ["S101", "S106", "S108"]
"scripts/*.py" = ["E402"]  # module imports after sys.path modification
"agents/hill_metrics/terrain_processor.py" = ["N806"]  # numpy conventions (X, Y variables)

[lint.isort]
known-first-party = ["agents"]
force-single-line = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"